[env:seeed-xiao-mbed-nrf52840-sense]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-mbed-nrf52840-sense
framework = arduino
monitor_speed = 115200
monitor_filters = time
lib_deps =
    seeed-studio/Seeed Arduino LSM6DS3
    Wire
    arduino-libraries/ArduinoBLE
extra_scripts = /home/sduttlinger/.platformio/scripts/gen_clangd.py
